# -*- coding: utf-8 -*-
"""NLP_Minip_SN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X23h-r9iD4yHkWmEWInbxMGzb9RSpBz8
"""

import pandas as pd

df = pd.read_csv("/IMDB Dataset.csv")

print(df.head())
print("Dataset Shape:", df.shape)
print("Columns:", df.columns)

# Check for missing values
print("Missing values:")
print(df.isnull().sum())

# Remove missing values
df = df.dropna()

# Convert reviews to lowercase
df["review"] = df["review"].str.lower()

print("\nDataset after cleaning:")
print(df.shape)

print("Sentiment Distribution:")
print(df["sentiment"].value_counts())

X = df["review"]
y = df["sentiment"]

print("Input data:", X.shape)
print("Target data:", y.shape)

y = y.map({
    "positive": 1,
    "negative": 0
})

print(y.head())

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X_train_tfidf = tfidf.fit_transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

print("Model training completed successfully!")

y_pred = model.predict(X_test_tfidf)

print("Predictions completed!")
print("First 20 predictions:")
print(y_pred[:20])

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy Percentage:", round(accuracy * 100, 2), "%")

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred,
    target_names=["Negative", "Positive"]
))

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6, 5))
plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted Sentiment")
plt.ylabel("Actual Sentiment")

plt.xticks([0, 1], ["Negative", "Positive"])
plt.yticks([0, 1], ["Negative", "Positive"])

for i in range(2):
    for j in range(2):
        plt.text(j, i, cm[i, j],
                 ha="center",
                 va="center")

plt.show()

def predict_sentiment(review):
    review_tfidf = tfidf.transform([review])
    prediction = model.predict(review_tfidf)[0]

    if prediction == 1:
        return "Positive"
    else:
        return "Negative"

review = "This movie was amazing and I really enjoyed it."

print("Review:", review)
print("Predicted Sentiment:", predict_sentiment(review))

review = "This movie was boring, terrible and a complete waste of time."

print("Review:", review)
print("Predicted Sentiment:", predict_sentiment(review))

review = "The acting was excellent and the story was fantastic."

print("Review:", review)
print("Predicted Sentiment:", predict_sentiment(review))